@baseUrl = http://localhost:8000/api/v1

###

@sign_in_auth = {{sign_in.response.body.auth}}

# @name sign_in
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "alimam@example.com",
  "password": "alimam@example.com"
}

###

@create_secret_id = {{create_secret.response.body.id}}

# @name create_secret
POST {{baseUrl}}/secrets/
Content-Type: application/json
Cookie: auth={{sign_in_auth}}

{
  "secret": "This is a secret message for testing",
  "expiresAt": "2025-12-31T23:59:59.000Z"
}

###

# @name get_secrets
GET {{baseUrl}}/secrets/
Cookie: auth={{sign_in_auth}}

###

# @name get_secret_by_id
GET {{baseUrl}}/secrets/{{create_secret_id}}
Cookie: auth={{sign_in_auth}}

###

# @name delete_secret
DELETE {{baseUrl}}/secrets/{{create_secret_id}}
Cookie: auth={{sign_in_auth}}

###

# @name delete_expired_secrets
DELETE {{baseUrl}}/secrets/expired/cleanup
Cookie: auth={{sign_in_auth}}
